/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://suau2udg25cmha6wk32tddn7oi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-h5jszaavnzcyrc3hcbgzk3ibpe",
    "aws_cognito_identity_pool_id": "us-east-1:69ab7f21-e709-48e8-b4fc-02c55806999e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_kOsLQrmIo",
    "aws_user_pools_web_client_id": "4gmfb5e1s91h2tvdktf4s47md8",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "PHONE_NUMBER"
    ],
    "aws_user_files_s3_bucket": "socail-media-app-storage-88cfae7c201047-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
